spring:
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/activiti6-demo?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: root
    password: root
  activiti:
    check-process-definitions: false
    async-executor-activate: false
    database-schema-update: false
    history-level: full
  freemarker:
    suffix: .ftl
    cache: false
    charset: UTF-8
    contentType: text/html

server:
  port: 8086